import './globals.css'

export const metadata = {
  title: 'Next.js App Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className='min-h-screen text-4xl'>{children}</div>
    </html>
  )
}
